obj-$(CONFIG_KVM) += kvm/
obj-y += pc.o pc_q35.o
obj-$(CONFIG_PIIX) += pc_piix.o
obj-y += pc_sysfw.o
obj-$(CONFIG_VTD) += x86-iommu.o intel_iommu.o
obj-$(CONFIG_AMD_IOMMU) += x86-iommu.o amd_iommu.o

obj-y += acpi-build.o
